sudo: required
services: docker
language: bash
branches:
  only:
  - master
before_script:
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
script:
- "./build.sh"
after_success:
- "./push.sh"
notifications:
  slack:
    rooms:
      secure: Qzpnc5iFpfBUTCgd6JLXI9tPxHMrJQa9TMoxrMBbkJru+8vN9OVlUO+QBT9t3AYqFK0BeXffgDper8MN6lWlevZcEHiodA2f/i8UcB1A2BXY2E/ht5sJlry/T+MT3h+JYX5DoU3lIB9K0dksSnZVNcUSsPXML4vFuZD5VGPFGdR7BUdcdFuwOEOIZ5dXuCixiDAeaWjz8QmJpV9aTzcF7uD8rSUSJXIVuOiHUumhxUF8X7v7v5Hn9GRITX6/tFsAcAnBiwaCnkWtLFdQKeoayiZSOCECLj362p1CsW8YGjIpC+i00HQacJ+0q42C5oH/scNwI3m/DlL+EEN+TTSGQJFdk6UD96bKbbm5Suc6IY6+FLbfMiZBQNEa32/AySjiHDNS5KggT6/dE99+gMdiQNkMl/9AXDjM0z9yU39uA3QdgE+dq7nY6IXSu5UKkGbvvoeeCc8Otjs69yjzDeajmT2GHsPeNJjNxEnUaRJymSz9A4pmvo+RrVV8Nov4N9zpSM4YTAa6lJuw9z4P+b/ZZsXm8yAA6UEJkJQWLhjhpJYNA0+/ZmohSb5lzvR8p2e7prGSjBl87CP0y9wOCjl4S0abynJ1M75scauoxOJxnMfiMQ/9P4ESLFGRJzMi6xZrIn5yNH3stlNKGzdJt9JhjO8M0X70suRZ+eHDmEDZIok=
